Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data type of the variables list_ and array_list.

The variable list_ is a Python list object, while array_list is a NumPy array object.

In [19]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [22]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list, dtype = int)

# original list_
for element in num_list:
    print(type(element))
    
# updated NumPy array
for element in num_array:
    print(type(element))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [6]:
num_array=np.random.randint(1,5,(6,6))
print('shape=',num_array.shape)
print(' size=',num_array.size)

shape= (6, 6)
 size= 36


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
z=np.zeros((3,3))
print('shape=',z.shape)
print(' size=',z.size)

shape= (3, 3)
 size= 9


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [15]:
z=np.eye(5,dtype=int)
print(z)
print('shape=',z.shape)
print(' size=',z.size)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
shape= (5, 5)
 size= 25
